### PR TITLE
Add paket.bootstrapper.exe

### LINKED ISSUE #1: Missing .paket\paket.exe
When running `build.cmd` I got this error `'.paket\paket.exe'` is not recognized as an internal or external command.

### PR DESCRIPTION
**Pull request by MangelMaxime**
Fix #1

### CODE REVIEW

**Comment by alfonsogarciacaro** [comment]
Thanks!

**Comment by forki** [comment]
Please use magic mode.

For this just rename the bootstrapper to paket.exe and use git add -f to
add it to the repo. Then no bootstrapper step is needed anymore. (still
keep paket.exe in gitignore)

Am 20.01.2017 4:04 nachm. schrieb "Alfonso Garcia-Caro" <
notifications@github.com>:

**Comment by alfonsogarciacaro** [comment]
@forki So besides your instructions, it's better to revert this PR?

**Comment by forki** [comment]
Yes.

**Pull request merged**
