### PR TITLE
Move UI tests to sdk

### PR DESCRIPTION
**Pull request by forki**
The UI tests were the last project that used old school MSBuild. We should port that

### CODE REVIEW

**Comment by forki** [comment]
Travis reports:

    error MSB3644: The reference assemblies for framework ".NETFramework,Version=v4.6.1" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies.


I know we solved this internally be installing the dev pack. @enricosada @davkean How do people do that on Travis?

**Comment by baronfel** [comment]
Enrico has the steps here: https://github.com/dotnet/netcorecli-fsc/wiki/.NET-Core-SDK-1.0#using-net-framework-as-targets-framework-the-osxunix-build-fails

You've got to set the FrameworkPathOverride and then you're set.

**Comment by forki** [comment]
Could you please send a pull request to update this? Would help a lot. Thx

Am 15.07.2017 3:09 nachm. schrieb "Chet Husk" <notifications@github.com>:

**Comment by baronfel** [comment]
I'm on mobile for the next hour and a half or so, but I could try after that.

**Comment by forki** [comment]
thanks for the PR. Next question: can someone test it on mac or linux locally?

**Comment by forki** [comment]
before merging: can someone confirm this is working on non-windows systems?

**Comment by baronfel** [comment]
Im heading home soon and can validate on osx

**Comment by forki** [comment]
Cool. I'm especially interested in the UI tests. Do they run?

**Comment by baronfel** [comment]
Can confirm that both server and client tests built, ran, and passed on mono 5.2, dotnet sdk 1.0.4, osx sierra 10.12.5! 🎆

**Comment by forki** [comment]
Awesome

**Comment by alfonsogarciacaro** [comment]
I'm having problems on Mac (**mono 5.0.1.1**, dotnet sdk 1.0.4, osx sierra 10.12.5) 😕 

- First, tests won't run (I get `error MSB3644: The reference assemblies for framework ".NETFramework,Version=v4.6.1" were not found.`) unless I run `sh build.sh --envvar FrameworkPathOverride /Library/Frameworks/Mono.framework/Vek/Versions/Current/lib/mono/4.5/` so I guess we need to set the environmental var in the build script for non-Windows platforms.
- After I do that, the tests fail with the following error:

```
[16:42:21 INF] EXPECTO? Running tests... <Expecto>
[16:42:21 DBG] 127.0.0.1 connected. Now has 1 connected
[16:42:21 INF] 127.0.0.1 8067 - [15/Jul/2017:02:42:21 Z] "GET / HTTP/1.1" 200 0
[16:42:22 DBG] 127.0.0.1 connected. Now has 2 connected
[16:42:22 DBG] 127.0.0.1 connected. Now has 3 connected
[16:42:22 DBG] 127.0.0.1 connected. Now has 4 connected
[16:42:22 INF] 127.0.0.1 8067 - [15/Jul/2017:02:42:22 Z] "GET /js/fetch.js HTTP/1.1" 200 0
[16:42:22 INF] 127.0.0.1 8067 - [15/Jul/2017:02:42:22 Z] "GET /js/shim.min.js HTTP/1.1" 200 0
[16:42:22 INF] 127.0.0.1 8067 - [15/Jul/2017:02:42:22 Z] "GET /css/site.css HTTP/1.1" 200 0
[16:42:22 INF] 127.0.0.1 8067 - [15/Jul/2017:02:42:22 Z] "GET /public/bundle.jsHTTP/1.1" 200 0
[ERROR - 2017-07-15T14:42:22.685Z] Session [cedce650-696b-11e7-9b09-9d3eb99ad3b1] - page.onError - msg: Error parsing url

  phantomjs://platform/console++.js:263 in error
[ERROR - 2017-07-15T14:42:22.685Z] Session [cedce650-696b-11e7-9b09-9d3eb99ad3b1] - page.onError - stack:
  r (http://localhost:8085/public/bundle.js:20)

  phantomjs://platform/console++.js:263 in error
[16:42:22 INF] 127.0.0.1 8067 - [15/Jul/2017:02:42:22 Z] "GET / HTTP/1.1" 200 0
[16:42:22 INF] 127.0.0.1 8067 - [15/Jul/2017:02:42:22 Z] "GET /css/site.css HTTP/1.1" 200 0
[16:42:22 INF] 127.0.0.1 8067 - [15/Jul/2017:02:42:22 Z] "GET /js/shim.min.js HTTP/1.1" 200 0
[16:42:22 INF] 127.0.0.1 8067 - [15/Jul/2017:02:42:22 Z] "GET /js/fetch.js HTTP/1.1" 200 0
[16:42:22 INF] 127.0.0.1 8067 - [15/Jul/2017:02:42:22 Z] "GET /public/bundle.jsHTTP/1.1" 200 0
[ERROR - 2017-07-15T14:42:22.848Z] Session [cedce650-696b-11e7-9b09-9d3eb99ad3b1] - page.onError - msg: Error parsing url

  phantomjs://platform/console++.js:263 in error
[ERROR - 2017-07-15T14:42:22.848Z] Session [cedce650-696b-11e7-9b09-9d3eb99ad3b1] - page.onError - stack:
  r (http://localhost:8085/public/bundle.js:20)

  phantomjs://platform/console++.js:263 in error
[ERROR - 2017-07-15T14:42:23.624Z] WebElementLocator - _handleLocateCommand - Element(s) NOT Found: GAVE UP. Search Stop Time: 1500129743587

  phantomjs://platform/console++.js:263 in error
[ERROR - 2017-07-15T14:42:28.357Z] WebElementLocator - _handleLocateCommand - Element(s) NOT Found: GAVE UP. Search Stop Time: 1500129748327

  phantomjs://platform/console++.js:263 in error
[ERROR - 2017-07-15T14:42:29.426Z] WebElementLocator - _handleLocateCommand - Element(s) NOT Found: GAVE UP. Search Stop Time: 1500129749391

  phantomjs://platform/console++.js:263 in error
[16:42:30 INF] 127.0.0.1 8067 - [15/Jul/2017:02:42:30 Z] "POST /api/users/loginHTTP/1.1" 200 259
[16:42:30 INF] 127.0.0.1 8067 - [15/Jul/2017:02:42:30 Z] "GET /api/wishlist/ HTTP/1.1" 200 281
[ERROR - 2017-07-15T14:42:30.555Z] WebElementLocator - _handleLocateCommand - Element(s) NOT Found: GAVE UP. Search Stop Time: 1500129750528

  phantomjs://platform/console++.js:263 in error
[16:42:31 INF] EXPECTO! 2 tests run in 00:00:09.5613175 – 2 passed, 0 ignored, 0 failed, 0 errored. ᕙ໒( ˵ ಠ ╭͜ʖ╮ ಠೃ ˵ )७ᕗ <Expecto>
[INFO  - 2017-07-15T14:42:31.181Z] ShutdownReqHand - _handle - About to shutdown
[16:42:31 DBG] Shutting down transport
[16:42:31 DBG] Shutting down transport
[16:42:31 DBG] Shutting down transport
[16:42:31 DBG] Shutting down transport
[16:42:31 DBG] Disconnected 127.0.0.1. 2 connected.
[16:42:31 DBG] Disconnected 127.0.0.1. 0 connected.
[16:42:31 DBG] Disconnected 127.0.0.1. 3 connected.
[16:42:31 DBG] Disconnected 127.0.0.1. 1 connected.
```

**Comment by baronfel** [comment]
You're right about that environment variable, I have it set in my profile so I forgot about it. The errors in the log don't seem to impact the overall test result though, expecto reports both client tests as passing.

**Comment by forki** [comment]
@baronfel can you please move the variable from Travis settings into build.fsx?

**Comment by alfonsogarciacaro** [comment]
@baronfel That's weird, for me the build fails because Expecto returns a non-zero exit code. This is what I get right below the log above:

```
Running build failed.
Error:
Expecto test of assembly '/Users/alfonsogarciacaronunez/dev/fable-suave-scaffold/test/UITests/bin/Release/UITests.exe' failed. Process finished with exit code 1.
```

**Pull request merged**
