### PR TITLE
Canopy cannot enter PW anymore

### PR DESCRIPTION
**Pull request by forki**
Something strange is happening with our UI tests.

wtf

@lefthandedgoat Why can't canopy enter the text anymore!?

### CODE REVIEW

**Comment by forki** [comment]
the PR shows that it's red on CI as well

**Comment by lefthandedgoat** [comment]
I am at a client then traveling home today, so I probably can't look at it until tomorrow.

If I clone, switch to canopy branch, what command do I run to repro?  just `sh build.sh`?

Just as a guess, because its all client side stuff, react/angular/whatever is doing some tricky stuff regarding the control and its not a simple input box anymore? or its intercepting the typing and not handling it properly, or the javascript is not done doing its thing before canopy starts typing (most likely)

This may slow it down enough to make it work

After `click "Login"`
Add `on "http://localhost:8085/#login"`

If none of that works I will look at it.

**Comment by forki** [comment]
@lefthandedgoat Weird thing is it worked at some point in time. Now it's broken.
regarding slowness:

    "#username" << "test"

^this should wait for #username to appear right?

that trick with `on` had no effect unfrotunately

**Comment by forki** [comment]
and yes "sh build.sh" should do the run

**Comment by lefthandedgoat** [comment]
Watching the video, it looks like it is waiting for it be there, and its typing before the page is 'done done'.  Because it does register the last few characters of `helllllllllllo`.

Selenium has its metrics on when the page is done loading, and once it is, it lets you type in boxes.  There is a mismatch between when selenium thinks the page is done, and when you can effectively start typing in the box.

Lots of cheesy ways to work around it, I will spend some time coming up with a clean one that works with your page.

**Comment by alfonsogarciacaro** [comment]
@lefthandedgoat Yes, React has the concept of [controlled components](https://facebook.github.io/react/docs/forms.html#controlled-components) for inputs in forms, so this may be causing problems though, as @forki says, it's weird it was working before.

**Comment by lefthandedgoat** [comment]
Working for me on OSX, will try tomorrow on windows VM.

**Comment by forki** [comment]
Yes AFAIK it's also working for @alfonsogcnunez

Am 16.03.2017 20:27 schrieb "Chris Holt" <notifications@github.com>:

**Comment by lefthandedgoat** [comment]
@forki 

I can reproduce it 100% of the time on Windows, but I can not figure out what is wrong.

Things I have tried:

Updated Chrome from 56 to 57
Updated Chrome driver from 2.27 to 2.28
Tried Latest firefox (it fails to write)
Went back to master (older canopy) still fails

There is one error in the javascript window, something about parsing urls.

The other thing I notice is that every key stroke has a logging of "UserMsg" `Updating: Model {Page: Page, Menu: Model, SubModel: SubModel} Navigable {Case: "UserMsg", Fields: Array(1)}`

Every keystroke from selenium is logged like this, but not everything is visible in the box, which makes me think it is not a Selenium problem.

For now I have to give up but I will keep thinking about it.

**Comment by forki** [comment]
@alfonsogcnunez I wonder if we use the wrong  text change event

Am 19.03.2017 02:27 schrieb "Chris Holt" <notifications@github.com>:

**Comment by alfonsogarciacaro** [comment]
@forki Hmm, could be. In the [React docs for controlled components](https://facebook.github.io/react/docs/forms.html#controlled-components) they use the `onChange` event while [fable-suave-scaffold uses `onInput`](https://github.com/fable-compiler/fable-suave-scaffold/blob/eb14b3d5193bde474efe1000ba4f195a3c4deeb1/src/Client/pages/Login.fs#L131). Maybe @et1975 can also help here=

**Comment by et1975** [comment]
Yeah, I had to use OnChange: https://github.com/fable-compiler/fable-elmish/blob/master/samples/react/todomvc/todomvc.fsx#L171

**Comment by alfonsogarciacaro** [comment]
Unfortunately, it seems this commit is still failing :/ https://github.com/fable-compiler/fable-suave-scaffold/commit/15255320b67994b44d4fe926098cd13e0ef636e0

**Comment by et1975** [comment]
I wonder if my `requestAnimationFrame` optimization messed it up... sending a PR.

**Comment by alfonsogarciacaro** [comment]
@et1975 fixed this in #76

**Pull request closed without merging**
