### PR TITLE
Adding execute permissions

### PR DESCRIPTION
**Pull request by monkieboy**

### CODE REVIEW

**Comment by forki** [comment]
@monkieboy I meant the chromedriver_linux64 and chromedriver_macOS files
they are renamed to chromedriver during the build depending on OS
but they need the execute flag
could you please ammend

**Comment by monkieboy** [comment]
Ok sorry, I will do those now.

**Comment by forki** [comment]
cool thanks!

**Comment by forki** [comment]
closed and reopened to trigger travis

**Comment by forki** [comment]
cool it actually started the chromedriver. thank you!

**Pull request merged**
