### PR TITLE
Upgrade to Fable 1.0

### PR DESCRIPTION
**Pull request by alfonsogarciacaro**
To @forki with ❤️

### CODE REVIEW

**Comment by forki** [comment]
NICE!

**Comment by forki** [comment]
wow it's green on first shot

**Comment by forki** [comment]
source

It's beautiful!

**Comment by alfonsogarciacaro** [comment]
We have the best project formats, the bestest project formats. It's HUGE! (but smaller at the same time)  

Thanks to @enricosada ;)

**Comment by enricosada** [comment]
👍 

a Q: the `src/Server/App.config` is needed for the ui tests? because the app.config is useless in .net core apps

**Comment by forki** [comment]
mhm it should probably be just removed.

**Pull request merged**
