### PR TITLE
Create zero diff to investigate #81

### PR DESCRIPTION
**Pull request by forki**

### CODE REVIEW

**Comment by enricosada** [comment]
seems ok..

**Comment by forki** [comment]
Weird. It was red yesterday.

**Comment by alfonsogarciacaro** [comment]
I'm no expert in Linux distributions, but it seems in order to use the dotnet SDK we're using the trusty container in Travis, which seems to be less stable with errors that come and go. We had the same problem in Fable some days ago.

**Comment by forki** [comment]
weird

**Pull request merged**
