### PR TITLE
Update to Fable 1.1.3

### PR DESCRIPTION
**Pull request by alfonsogarciacaro**
Updates to Fable _stablish_ 1.1.3, many `prerelease` tags have been removed from paket.dependencies ;) All the dependencies like Fable.Elmish, Fable.React have been also updated with the new Fable.Import.Browser split from Fable.Core.

`build Run` works locally for me, just `build` breaks because it says it cannot find the Expecto assembly, don't know why. Let's see what the CI servers say.

### CODE REVIEW

**Comment by alfonsogarciacaro** [comment]
Not sure why Travis is failing here. Any idea @forki?

**Comment by forki** [comment]
Says yarn crashed

**Comment by alfonsogarciacaro** [comment]
Argh, yarn is giving a lot of problems in Travis 😁 @forki Should we use npm 5 which also has lock files?

**Comment by forki** [comment]
I'm not allowed to comment on package managers. My karma is about to enter negative numbers

**Comment by mastoj** [comment]
I wonder if this was the same issue I mentioned for you at NDC @forki ? I did a run and it said `yarn` was missing, added a stupid line that printed some text and it all started working as expected. I have no clue what was broken or what fixed it.

**Comment by alfonsogarciacaro** [comment]
Apparently the problem was adding the `phantomjs` dependency to package.json. I really have no idea how that line got there 😕 

After removing it, tests pass so I'm merging :+1:

**Pull request merged**
