### PR TITLE
Run Tests on CI

### PR DESCRIPTION
**Pull request by forki**
- [x] runs on Windows
- [ ] runs on mono

### CODE REVIEW

**Comment by haf** [comment]
Is the at-mention intended to say; your software is slightly broken, missing some regular expressions?

**Comment by forki** [comment]
@haf nope, but I saw you comment on different issue with selenium on mono. Thought you might know something. 

In fact I don't use regular exceptions in the code at all. This is only indirectly via canopy + selenium. It seems to fail during compile because some dependency is using it and mono can't find it. I'm lost

**Comment by lefthandedgoat** [comment]
I am trying to repro on OSX:

I clone
Switch to `tests` branch
run `sh build.sh run`

Its failing on dotnetcore restore

```
/Users/cholt1/.local/share/dotnetcore/dotnet restore
﻿  Paket version 4.0.0-beta014
   - /Users/cholt1/projects/fable-suave-scaffold/src/Server/obj/Server.fsproj.references already up-to-date
  1 second - ready.
  Restoring packages for /Users/cholt1/projects/fable-suave-scaffold/src/Server/Server.fsproj...
  Restoring packages for /Users/cholt1/projects/fable-suave-scaffold/src/Server/Server.fsproj...
  Restoring packages for /Users/cholt1/projects/fable-suave-scaffold/src/Server/Server.fsproj...
/Users/cholt1/.local/share/dotnetcore/sdk/1.0.0-rc4-004771/NuGet.targets(97,5): error : Unable to load the service index for source https://api.nuget.org/v3/index.json. [/Users/cholt1/projects/fable-suave-scaffold/src/Server/Server.fsproj]
/Users/cholt1/.local/share/dotnetcore/sdk/1.0.0-rc4-004771/NuGet.targets(97,5): error :   The type initializer for 'System.Net.Http.CurlHandler' threw an exception. [/Users/cholt1/projects/fable-suave-scaffold/src/Server/Server.fsproj]
```

How do I get it to try to build with mono instead of dnc?

**Comment by forki** [comment]
@haf wow wtf nuget?! Maybe it's temporarily down? Anyways server side is not made for mono in this sample - I'm not even sure if the new fsproj format would work with xbuild!?

**Comment by lefthandedgoat** [comment]
@forki 

The link it says it can not hit is not down for me
https://api.nuget.org/v3/index.json

is `sh build.sh run` the right steps to reproduce the Regex problem?

OSX El capitan, mono x86 4.8.0 btw

**Comment by forki** [comment]
yes I think that's what @mastoj did as well

**Comment by lefthandedgoat** [comment]
I just re-read and noticed this `Anyways server side is not made for mono in this sample`

Does that mean I can just run `sh build.sh BuildClient`

If so, that works for me:

```
Finished Target: BuildClient

---------------------------------------------------------------------
Build Time Report
---------------------------------------------------------------------
Target              Duration
------              --------
Clean               00:00:00.0020384
InstallDotNetCore   00:00:00.1165181
InstallClient       00:00:01.7644098
AssemblyInfo        00:00:00.0259243
BuildClient         00:00:08.3704362
Total:              00:00:10.3174624
Status:             Ok
```

**Comment by forki** [comment]
no this only builds the fable client side. You also need the server side (which is suave on .NET core).

**Comment by lefthandedgoat** [comment]
Ok then this should be sufficient to repro? `sh build.sh Build`

**Comment by lefthandedgoat** [comment]
Ok, I will try again tonight (like 8 hours from now), from a different internet connection to see if that helps.

**Comment by lefthandedgoat** [comment]
Full stack, I think its something to do with loading a DLL, similar to your problem?

```
Finished Target: BuildClient
Starting Target: Build (==> BuildClient)
/Users/cholt1/.local/share/dotnetcore/dotnet restore
﻿  Paket version 4.0.0-beta014
   - /Users/cholt1/projects/fable-suave-scaffold/src/Server/obj/Server.fsproj.references already up-to-date
  1 second - ready.
  Restoring packages for /Users/cholt1/projects/fable-suave-scaffold/src/Server/Server.fsproj...
  Restoring packages for /Users/cholt1/projects/fable-suave-scaffold/src/Server/Server.fsproj...
  Restoring packages for /Users/cholt1/projects/fable-suave-scaffold/src/Server/Server.fsproj...
/Users/cholt1/.local/share/dotnetcore/sdk/1.0.0-rc4-004771/NuGet.targets(97,5): error : Unable to load the service index for source https://api.nuget.org/v3/index.json. [/Users/cholt1/projects/fable-suave-scaffold/src/Server/Server.fsproj]
/Users/cholt1/.local/share/dotnetcore/sdk/1.0.0-rc4-004771/NuGet.targets(97,5): error :   The type initializer for 'System.Net.Http.CurlHandler' threw an exception. [/Users/cholt1/projects/fable-suave-scaffold/src/Server/Server.fsproj]
/Users/cholt1/.local/share/dotnetcore/sdk/1.0.0-rc4-004771/NuGet.targets(97,5): error :   The type initializer for 'Http' threw an exception. [/Users/cholt1/projects/fable-suave-scaffold/src/Server/Server.fsproj]
/Users/cholt1/.local/share/dotnetcore/sdk/1.0.0-rc4-004771/NuGet.targets(97,5): error :   The type initializer for 'HttpInitializer' threw an exception. [/Users/cholt1/projects/fable-suave-scaffold/src/Server/Server.fsproj]
/Users/cholt1/.local/share/dotnetcore/sdk/1.0.0-rc4-004771/NuGet.targets(97,5): error :   The type initializer for 'CryptoInitializer' threw an exception. [/Users/cholt1/projects/fable-suave-scaffold/src/Server/Server.fsproj]
/Users/cholt1/.local/share/dotnetcore/sdk/1.0.0-rc4-004771/NuGet.targets(97,5): error :   Unable to load DLL 'System.Security.Cryptography.Native.OpenSsl': The specified module could not be found. [/Users/cholt1/projects/fable-suave-scaffold/src/Server/Server.fsproj]
/Users/cholt1/.local/share/dotnetcore/sdk/1.0.0-rc4-004771/NuGet.targets(97,5): error :    (Exception from HRESULT: 0x8007007E) [/Users/cholt1/projects/fable-suave-scaffold/src/Server/Server.fsproj]
Running build failed.
Error:
System.Exception: Restore failed
  at FSI_0005.Build+clo@181-22.Invoke (Microsoft.FSharp.Core.Unit _arg4) [0x0002c] in <ebcebd40faa44b5f9ad1f566548a37fe>:0 
  at Fake.TargetHelper+targetFromTemplate@195[a].Invoke (Microsoft.FSharp.Core.Unit unitVar0) [0x00001] in <58aaff2accf1c534a74503832affaa58>:0 
  at Fake.TargetHelper.runSingleTarget (Fake.TargetHelper+TargetTemplate`1[a] target) [0x00040] in <58aaff2accf1c534a74503832affaa58>:0 
```

This line being the most important?

```
/Users/cholt1/.local/share/dotnetcore/sdk/1.0.0-rc4-004771/NuGet.targets(97,5): error :   Unable to load DLL 'System.Security.Cryptography.Native.OpenSsl': The specified module could not be found. [/Users/cholt1/projects/fable-suave-scaffold/src/Server/Server.fsproj]
```

**Comment by forki** [comment]
@mastoj did you see that as well? I mean the travis is clearly working at that stage!?

**Comment by mastoj** [comment]
@forki, I only saw the regular expressions error.

**Comment by noklesta** [comment]
@lefthandedgoat I got the same error (on macOS Sierra) and found that I needed to symlink the OpenSSL libraries from the Homebrew installation into /usr/local/lib as described here: [https://www.microsoft.com/net/core#macos](https://www.microsoft.com/net/core#macos). After that running `./build.sh run` works like a charm :)

Still seeing the regular expression error when running the tests, though...

**Comment by lefthandedgoat** [comment]
Thanks @noklesta after doing those steps it works for me.

```
Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:01.30
Finished Target: Build

---------------------------------------------------------------------
Build Time Report
---------------------------------------------------------------------
Target              Duration
------              --------
Clean               00:00:00.0019479
InstallDotNetCore   00:00:00.1416195
InstallClient       00:00:02.0724578
AssemblyInfo        00:00:00.0325875
BuildClient         00:00:08.5791233
Build               00:00:05.6935362
Total:              00:00:16.5610080
Status:             Ok
-----------------------------------
```

And with the `Run` argument it pops open a browser and says `Welcome`

Can you please provide full stack of the regex error you see?

And run this and post the response? `mono -V`

My results are

```
Mono JIT compiler version 4.8.0 (mono-4.8.0-branch/f5fbc32 Mon Nov 14 14:10:00 EST 2016)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           normal
	SIGSEGV:       altstack
	Notification:  kqueue
	Architecture:  x86
	Disabled:      none
	Misc:          softdebug 
	LLVM:          yes(3.6.0svn-mono-master/8b1520c)
	GC:            sgen
```

**Comment by lefthandedgoat** [comment]
I did a bunch of research and while, I can repro, I don't know what the source of the problem is.

I found this which looks similar:

http://stackoverflow.com/questions/17829171/field-not-found-system-text-reg-u-lar-ex-pres-sions-regex-in-ter-nal-matchtime

and it links to this:

http://stackoverflow.com/questions/8456779/field-not-found-exception-with-compiled-dll-regular-expression

It looks like a mixing of .net40 compiled dlls and .net 45 compiled ones and backwards compat problems.

I don't think that canopy is the source of the problem, because it does not use Regex.IsMatch, only Regex.Match 

https://github.com/lefthandedgoat/canopy/blob/42470791fe8b89e6c19788801c846b1ccf8af62c/src/canopy/canopy.fs#L61

Could it be that canopy is built against FSharp.Core 3.0.2?

**Comment by forki** [comment]
@noklesta could you please send a Pull request to the readme and explaining things in the requirements section. Thanks

**Comment by forki** [comment]
@lefthandedgoat thanks for the tip. I downgraded fsproj to .NET 4.5 and everything seems to work. So I wonder if your sample app works with .NET 4.6.1

**Comment by forki** [comment]
Ok I finaly found the real issue. We can't use `nuget Selenium.WebDriver.ChromeDriver` because reasons.

So I looked at canopyStarterKit and just did the same and added binaries. (which is weird!)
Anyways it's nearly working, but the build still can't find chrome driver

**Comment by forki** [comment]
ok it seems execute flags were missing. Now I'm stuck in https://github.com/fable-compiler/fable-suave-scaffold/pull/51

**Comment by forki** [comment]
Error: The HTTP request to the remote WebDriver server for URL http://localhost:38293/session timed out after 60 seconds.

**Comment by forki** [comment]
@lefthandedgoat ok I'm stuck again

**Comment by lefthandedgoat** [comment]
@forki that error is generally from a mismatch between chromedriver and chrome.

(getting latest code, everything builds and the tests run for me with chrome 56)

chromedriver is good for versions x to x + 2 generally.

Look here and you can see that chromedriver 2.27 is good for 54-56

https://sites.google.com/a/chromium.org/chromedriver/downloads

You are using 2.26 which is probably good for 54-56 also, or maybe 53-55.

Your problem is probably that the version of chrome on your build server is older, probably 52 or lower, and chromedriver can't talk to it correctly.  Update chrome and it should work.

**Comment by forki** [comment]
> Update chrome and it should work

mhm. that's out of my hands since it's travis. But that said: It's on the CI server so it should use phantom. Can we make it use phantom?

**Comment by lefthandedgoat** [comment]
yes do `start phantomJS` instead of `start chrome`

And download phantom, http://phantomjs.org/, and do the same thing where you copy the exe to the bin directory etc. and set `phantomJSDir` to executing directory

**Comment by forki** [comment]
can we use the phantom nuget package?

**Comment by lefthandedgoat** [comment]
Also, if travis is running linux, then its probably headless, and you need to use `xvfb` (x server virtual frame buffer) and it will create a fake X, which will let chrome actually launch.

This article tells you how to set up travis for that https://docs.travis-ci.com/user/gui-and-headless-browsers/

**Comment by lefthandedgoat** [comment]
This section: `Using xvfb to Run Tests That Require a GUI`

It mentions that firefox is installed on all environments, but it does not mention chrome.

Firefox is in a really weird spot right now with UI automation, versions 47 and below do not require a driver like chromedriver, and newer versions do.  Unfortunately not everything works on newer versions, I personally avoid it.

UI Automation is a hot mess btw =*(

**Comment by forki** [comment]
I tried to use phantom in #51, but I now have an issue on my machine

image

It looks like phantom did not load the react code?!

**Comment by forki** [comment]
@lefthandedgoat did you see that before?

**Comment by lefthandedgoat** [comment]
I never use phantom, I generally just use chrome.  People have differing opinions on the quality of phantom.

After doing some reading I think the best thing for you to do is to install chrome on your travis instance.

Follow instructions here on how to install it on chrome:

http://coderscoffeehouse.com/tech/2017/01/17/headless-front-end-testing-on-linux-using-fsharp.html

I think you put it in your yml file, like here: https://docs.travis-ci.com/user/gui-and-headless-browsers/

Install Chrome
Start xfvb instance
Run tests

"Should work"

If it does not, tonight I can try to setup a travis instance for canopStarterKit and give you the working config.

**Comment by forki** [comment]
Yes Travis on the starter kit would help me a lot.

Am 22.02.2017 18:49 schrieb "Chris Holt" <notifications@github.com>:

**Comment by lefthandedgoat** [comment]
@forki Got it, I had to cancel the build because it has a Console.ReadKey and hung there, but it ran the tests

https://travis-ci.org/lefthandedgoat/canopyStarterKit/builds/204461830

https://github.com/lefthandedgoat/canopyStarterKit/blob/master/.travis.yml

Just a couple new sections and you should be working.

Hope this helps, just @ me and I can help more if need be!

**Pull request merged**
