### PR TITLE
Fix minor html linting issues

### PR DESCRIPTION
**Pull request by quintusm**
- Add a title
- Fix the meta http-equiv item
- Use tabs consistently

### CODE REVIEW

**Comment by alfonsogarciacaro** [comment]
Thanks!

**Comment by quintusm** [comment]
HI, I am sorry, I am a bit obsessive compulsive about stuff.  If you don't want to bother with trivia like this, just nuke the pull request, I wont be offended.

**Comment by forki** [comment]
@quintusm keep them coming! we appreciate OCD changes

**Comment by quintusm** [comment]
Wow, that was fast.  Are you using some kind of automated process to merge pull requests?

**Comment by alfonsogarciacaro** [comment]
Nah, I just happened to see it and clicked the button ;) Optimistic merging FTW!

> I did have a look btw ;)

**Pull request merged**
