### PR TITLE
WIP: Explore client code structure

### PR DESCRIPTION
**Pull request by bentayloruk**
I'm just getting up to speed on Elm and Elmish, via this scaffold and lots of great Elm examples on the internet.  I've found some parts of the code/structure of this base app very clear and others a little confusing.  Therefore, as part of my learning, I thought I would try and make some of this more obvious _to me_, and try and make it as clear as some of the very polished Elm examples.  I'm hoping I can use my newbie experience to help others that follow me.

Hopefully, some of the changes make sense and might benefit the code base.  Alternatively, I could be running before I can walk!  This PR is just a start.  Ultimately, the aim would be to contribute to creating a rock solid structure for a new SPA, along with docs clearly suggesting how to use it (with the usual Elm caveat of *do what's right for you man*!).  Anyway, I thought I'd raise a PR and see if it can start a discussion.  *If it's better done elsewhere, let me know*.

Changes are:  

Tried to improve the encapsulation of the child apps (i.e. pages and
menu component):

* Moved the child app message types into the child app files.  Think
this is an easier read for newbies and is similar to lot of Elm
examples.  [Example](https://github.com/bentayloruk/fable-suave-scaffold/blob/structure/src/Client/pages/WishList.fs).
* Commented the page files as per Kris Jenkins' [suggestion of Model,
Message, REST, State, View](http://blog.jenkster.com/2016/04/how-i-structure-elm-apps.html).
* Removed knowledge of App level message DU from child apps, by putting the
App level message DU in a file after the child apps in the fsproj
compilation order.  Made it the responsibility of the App to map child
message types to App message types (done with composing the dispatch
function and the child msg ctor).  *Done this under the assumption that
the child app should only know and communicate with its own messages.*

Other changes:

* Put Menu in a components folder, to reduce confusion about it being a
Page.  Seen this structure in other Elm apps.
* Put the 'global' model types in root Model.fs.  Not sure this is
quite right yet, for example, should a child component know about other
pages?  Anyway, OK for now.  Left the App specific model types in
App.fs.  This structure makesense in relation to the F# compilation order.

### CODE REVIEW

**Comment by alfonsogarciacaro** [comment]
Thanks for the suggestions, @bentayloruk! Maybe @et1975 and @MangelMaxime can also have a look?

**Comment by MangelMaxime** [comment]
The suggestions made in this PR will be included into the new "template" version.

To not loose the work already done by @bentayloruk I will take this PR branch as a start for working on #122 

I would prefer not merge this PR or at least not update it further as I will have a hard time keeping the template version sync with the new commits :) I promise, I am working on it today so I should start a new PR to contribute as a team on it this evening. :)

**Comment by bentayloruk** [comment]
Sounds good to me.  I've already started working on other "improvements", so I will pause for now and head on over to #122 to see what's up!

**Comment by MangelMaxime** [comment]
Sure, I will ping you with the new PR so we will be able to speak on the improvement here :).

I am closing this PR as we will add this work in another.

**Pull request closed without merging**
